openapi: 3.0.3

info:
  title: MagicBoard - Rest API
  description: |-
    the rest API for the MagicBoard  
  version: "1.0"

servers:
  - url: http://64.227.121.226

tags:
  - name: Board
    description: Related to boards which includes the functions for creating and managing boards (UID's)

paths:
  /v1/board/validate_uid:
    get:
      tags:
        - Board
      summary: Validates a board UID
      description: Takes a board UID and validates it.
      operationId: validateUID
      parameters:
        - $ref: '#/components/parameters/board_uid'
      responses:
        '200':
          description: Whether Board UID is valid.
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '400':
          $ref: '#/components/responses/board_uid_missing'

  /v1/board/inpect_UID:
    get:
      tags:
        - Board
      summary: Checks whether a UID exists
      description: Takes a board UID and checks whether the board exists.
      operationId: checkUID
      parameters:
        - $ref: '#/components/parameters/board_uid'
      responses:
        '200':
          description: Whether the Board exists, based on Board UID.
          content:
            application/json:
              schema:
                type: boolean
                example: true
        '400':
          $ref: '#/components/responses/board_uid_missing'

  /v1/board/create:
    post:
      tags:
        - Board
      summary: Creates a new board
      operationId: createBoard
      responses:
        '200':
          description: Returns Board UID of successfully create board.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/board_create_result'

  /v1/board/join:
    get:
      tags:
        - Board
      summary: Get invite to websocket server
      operationId: joinBoard
      parameters:
        - $ref: '#/components/parameters/board_uid'
      responses:
        '200':
          description: Board joined??
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/board_join_result'

components:
  schemas:
    board_uid:
      type: string
      minLength: 6
      maxLength: 6
      example: AB4D3G
    board_create_result:
      type: object
      properties:
        board_uid:
          $ref: '#/components/schemas/board_uid'
    board_join_result:
      type: object
      properties:
        host:
          type: string
          format: ip
          example: 127.0.0.1
        port:
          type: integer
          example: 25565

  parameters:
    board_uid:
      name: board_uid
      in: query
      description: UID of a board.
      required: true
      schema:
        $ref: '#/components/schemas/board_uid'

  responses:
    board_uid_missing:
      description: Board UID was not supplied.
      content:
        text/html:
          schema:
            type: string
            example: <p>board_uid parameter missing.</p>
